config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[show create edit update destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render 'edit'
    end
  end

  def destroy
    @flat.destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit "Add new flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>All our flats</h1>
  </div>
</div>
<div class="row">
  <div class="column">
    <p>All <%= Flat.all.size  %> flats.</p>
  </div>
</div>
<div class="row">
  <% @flats.each do |flat| %>
  <div class="col-md-4">
    <div class="flat-card">
      <div class="flat-card-image"></div>
      <div class="flat-card-content">
        <div class="flat-card-title">
          <h4><%= flat.name %></h4>
        </div>
        <p><%= flat.address %></p>
        <div class="flex">
          <div class="flex">
            <i class="material-icons me-2">Guests: </i>
            <span><%= flat.number_of_guests %></span>
          </div>
          <div class="flex ms-3">
            <i class="material-icons me-2">Price: </i>
            <span><%= flat.price_per_night %></span>
          </div>
        </div>
      </div>
      <div class="card-actions">
        <%= link_to 'More info', flat_path(flat) %>
        <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 text-warning' %>
        <%= link_to 'Remove', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ms-3 text-danger' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a href="/flats" class="navbar-brand">Simple Airbnb</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="ms-auto flex">
            <a href="flats/new" class="btn btn-outline-primary my-2 my-sm-0 ms-2">Add flat</a>
          </div>
        </div>
      </div>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>